// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVM6OAr8y22_Ga9F3czTuWAervaTQydHQ',
    appId: '1:532605184931:web:310e6b50fdb1952b3d4816',
    messagingSenderId: '532605184931',
    projectId: 'logistic-9d758',
    authDomain: 'logistic-9d758.firebaseapp.com',
    storageBucket: 'logistic-9d758.appspot.com',
    measurementId: 'G-99FJD7PTCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8RpGK5tl9bAulpXM8q8n4Y5H7ZXYgTQg',
    appId: '1:532605184931:android:18da90ad7f2b7a243d4816',
    messagingSenderId: '532605184931',
    projectId: 'logistic-9d758',
    storageBucket: 'logistic-9d758.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMMk-5Anrp0qE4xqkh8C0PsyUax1x-Qpg',
    appId: '1:532605184931:ios:f076cbb8873f19253d4816',
    messagingSenderId: '532605184931',
    projectId: 'logistic-9d758',
    storageBucket: 'logistic-9d758.appspot.com',
    iosBundleId: 'io.xenex.xengistic.or',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMMk-5Anrp0qE4xqkh8C0PsyUax1x-Qpg',
    appId: '1:532605184931:ios:b23dd8fcec757dd93d4816',
    messagingSenderId: '532605184931',
    projectId: 'logistic-9d758',
    storageBucket: 'logistic-9d758.appspot.com',
    iosBundleId: 'io.xenex.xengistic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVM6OAr8y22_Ga9F3czTuWAervaTQydHQ',
    appId: '1:532605184931:web:b0c3aa229d0421ab3d4816',
    messagingSenderId: '532605184931',
    projectId: 'logistic-9d758',
    authDomain: 'logistic-9d758.firebaseapp.com',
    storageBucket: 'logistic-9d758.appspot.com',
    measurementId: 'G-L6XVQLMCG9',
  );
}
